import Image from 'next/image'
import Head from 'next/head';
import Sidebar from '../../components/Sidebar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Whatsapp</title>
        <meta name="description" content="Generated by " />
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      </Head>

      <Sidebar />
    </div>
  )
}
